##################################################
## Project: RNASeq
## Purpose: configuration file
## Date: July 2021
## Author: Berk Gürdamar
##################################################

analysis:  ### "sample_name"_"lane".fastq.qz, lane = 1,2
  sample: [SRR12976448]
  control: []
  type: paired
  output: pathway_enrichment ### trimming, mapping, quantification, diff_exp, pathway_enrichment
  is_fastqc: "NO" ### YES, NO
  data_dir: /mnt/d/atom/projects/rnaseq/sample

required:
  threads: 6
  trimgalore:
    quality: 20
    length: 35
  star:
    index_whole_genome: /mnt/d/atom/projects/rnaseq/required_files/reference_genome.fa
    star_gtf: /mnt/d/atom/projects/rnaseq/required_files/gtf_file.gtf
    star_index: /mnt/d/atom/projects/rnaseq/index_genome
    genomeSAsparseD: 3
    genomeGenerate: genomeGenerate
    limitGenomeGenerateRAM: 164282414959
    genomeSAindexNbases: 14
    genomeChrBinNbits: 18
    outSAMtype: BAM Unsorted
    twopassMode: Basic
    twopass1readsN: -1
    readFilesCommand: zcat
  salmon:
    library_type: A
  pathfindr:
    p_val_threshold: 0.1
    iterations: 10
    gene_name_converter: /mnt/d/atom/projects/rnaseq/required_files/mart_export.txt

paths:
  deseq_script_path: /mnt/d/atom/projects/rnaseq/scripts
  pathfindr_script_path: /mnt/d/atom/projects/rnaseq/scripts
