analysis:
  control: b, d
  data_dir: /home/bgurdamar/tubitak_rnaseq/samples
  is_fastqc: 'YES'
  matched_samples: a_b, c_d
  output: diff_exp
  replicate: 'YES'
  sample: a, c
  type: single
required:
  pathfindr:
    gene_name_converter: /mnt/d/atom/projects/rnaseq/scripts/mart_export.txt
    iterations: 10
    p_val_threshold: 0.1
  salmon:
    library_type: A
  star:
    genomeChrBinNbits: 18
    genomeGenerate: genomeGenerate
    genomeSAindexNbases: 14
    genomeSAsparseD: 3
    index_whole_genome: /home/bgurdamar/tubitak_rnaseq/references/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    limitGenomeGenerateRAM: 164282414959
    outSAMtype: BAM Unsorted
    readFilesCommand: zcat
    star_gtf: /home/bgurdamar/tubitak_rnaseq/references/Homo_sapiens.GRCh38.104.gtf
    star_index: /home/bgurdamar/tubitak_rnaseq/index_genome
    twopass1readsN: -1
    twopassMode: Basic
  threads: 16
  trimgalore:
    length: 35
    quality: 20
